### ISSUE TITLE
Cannot build on iOS Xcode for RN 0.72.14

### ISSUE THREAD

**Issue by IHadinoto** [lukaszkurantdev/react-native-fast-opencv#39]
Hi there, I am try to build react-native-fast-opencv with RN0.72.14 but I am not successful. I am following the installation instructions:
`npm install react-native-fast-opencv`
`cd ios`
`pod install`

This downloads react-native-fast-opencv version 0.3.3. Then, I try to run it on Xcode and I get the following error in FOCV_Storage.hpp line 55 `if(!items.contains(key)) {`:
> No member named 'contains' in 'std::unordered_map<std::string, std::any>'
![image](https://github.com/user-attachments/assets/07ccca93-5e9d-4edd-8430-6df2530946f8)

Since line 56 is a TODO, I figured I could comment out lines 55-57, but instead I get all these errors in jsi:
> .../ios/Pods/Headers/Public/hermes-engine/jsi/jsi.h:1102:43 No matching function for call to 'kindOf'

> .../ios/Pods/Headers/Public/hermes-engine/jsi/jsi.h:1104:9 Static assertion failed due to requirement 'std::is_base_of<facebook::jsi::Symbol, cv::MatSize &>::value || std::is_base_of<facebook::jsi::BigInt, cv::MatSize &>::value || std::is_base_of<facebook::jsi::String, cv::MatSize &>::value || std::is_base_of<facebook::jsi::Object, cv::MatSize &>::value': Value cannot be implicitly move-constructed from this type

> .../ios/Pods/Headers/Public/hermes-engine/jsi/jsi.h:1104:9 Static assertion failed due to requirement 'std::is_base_of<facebook::jsi::Symbol, unsigned char &>::value || std::is_base_of<facebook::jsi::BigInt, unsigned char &>::value || std::is_base_of<facebook::jsi::String, unsigned char &>::value || std::is_base_of<facebook::jsi::Object, unsigned char &>::value': Value cannot be implicitly move-constructed from this type

> .../ios/Pods/Headers/Public/hermes-engine/jsi/jsi.h:1104:9 Static assertion failed due to requirement 'std::is_base_of<facebook::jsi::Symbol, float &>::value || std::is_base_of<facebook::jsi::BigInt, float &>::value || std::is_base_of<facebook::jsi::String, float &>::value || std::is_base_of<facebook::jsi::Object, float &>::value': Value cannot be implicitly move-constructed from this type

> .../ios/Pods/Headers/Public/hermes-engine/jsi/jsi.h:1109:26 Cannot allocate reference type 'cv::MatSize &' with new

> .../ios/Pods/Headers/Public/hermes-engine/jsi/jsi.h:1109:26 Cannot allocate reference type 'unsigned char &' with new

> ...ios/Pods/Headers/Public/hermes-engine/jsi/jsi.h:1109:26 Cannot allocate reference type 'float &' with new

![image](https://github.com/user-attachments/assets/b8ec7957-3387-40b2-98a3-34494760fd84)

Would you have any suggestions please?

Thank you very much.

**Comment by lukaszkurantdev** [comment]
@IHadinoto Hi, please try to modify C++ Language Dialect in your target Build Settings. It looks like you use older standard of C++.
You can change it here:
![Zrzut ekranu 2024-11-22 o 07 48 40](https://github.com/user-attachments/assets/554c22de-bcc2-4f60-b138-eeacf7cc8334)

Be sure that its equal (or higher) C++20

**Comment by IHadinoto** [comment]
Hi @lukaszkurantdev, thank you for your response. Following your instructions and trying some things out on my own,

**Comment by IHadinoto** [comment]
Hi @lukaszkurantdev, thank you for your response. Following your instructions and trying some things out on my own, I was able to solve the FOCV_Storage.hpp line 55 issue, but I was not able to solve the jsi issues. I can provide steps for a minimal reproducible example below:

1. Open VSCode into an empty folder. 
2. In the VSCode terminal, run `npx react-native@0.72.14 init AwesomeProject --version 0.72.14`
3. Run the following commands:
`cd AwesomeProject`
`npm install react-native-fast-opencv --save`
`cd ios`
`pod install --repo-update`
4. Open Xcode, and open the .xcworkspace file
5. Set the Team in the Signing & Capabilities tab
6. Change the C++ version on the Pods tab to c++20
7. Click on Run

The aforementioned issues should come up. Please let me know if you need any additional information.

**Comment by IHadinoto** [comment]
Replacing 0.72.14 with 0.74.4 solved the issue for me. I suppose RN 0.72 and earlier is not supported with this library
